"""Public SDK surface for Evalt."""

from .core import (
    BudgetExceeded,
    Client,
    DraftAnswer,
    Evalt,
    Example,
    GateReport,
    ImageInput,
    ModelResult,
    MonitorResult,
    OptimizationResult,
    ProviderError,
    RequestEnvelopeDriftWarning,
    RouteVersionMismatch,
    RolePlan,
    RoutedAnswer,
    Suite,
    SuiteDraft,
    Turn,
    check_result,
    multimodal_input,
    select_role_plan,
)
from .reporting import (
    RegressionGateReport,
    check_regression,
    compare_results,
    render_comparison_html,
    render_html_report,
    render_junit_report,
    write_reports,
)
from .library import EvidenceLibrary, LibraryEntry, resolve_evidence_reference
from .scorers import (
    CommandScorer,
    CustomScorerError,
    ScoreRequest,
    ScoreResult,
    Scorer,
)

__all__ = [
    "BudgetExceeded",
    "Client",
    "DraftAnswer",
    "Evalt",
    "Example",
    "GateReport",
    "ImageInput",
    "ModelResult",
    "MonitorResult",
    "OptimizationResult",
    "ProviderError",
    "RequestEnvelopeDriftWarning",
    "RouteVersionMismatch",
    "RolePlan",
    "RoutedAnswer",
    "Suite",
    "SuiteDraft",
    "Turn",
    "check_result",
    "multimodal_input",
    "select_role_plan",
    "RegressionGateReport",
    "check_regression",
    "compare_results",
    "render_comparison_html",
    "render_html_report",
    "render_junit_report",
    "write_reports",
    "EvidenceLibrary",
    "LibraryEntry",
    "resolve_evidence_reference",
    "CommandScorer",
    "CustomScorerError",
    "ScoreRequest",
    "ScoreResult",
    "Scorer",
]

__version__ = "0.10.31"
